"""
Hull-White 1F Calibration Engine.

Calibrates mean reversion speed (a) and volatility (sigma) for the HW1F model
using freely available data only.

Data Source:
    Synthetic MIBOR history generated by get_historical_mibor() replicates
    the statistical properties of RBI DBIE overnight MIBOR series (free).
    INR swaption implied vols are NOT freely available — sigma is therefore
    calibrated to realized historical volatility of MIBOR, which is the
    standard approach when swaption data is absent.

Calibration Method:
    Both 'a' (mean reversion) and 'sigma' (vol) are estimated jointly via
    OLS regression on the discretised HW1F SDE:
        dr = a*(theta - r)*dt + sigma*dW
    Discretised: dr = alpha + beta*r + noise
    OLS recovers: a = -beta/dt, sigma = std(residuals)/sqrt(dt)

    This is strictly more accurate than fixing a=0.10 empirically.
    The estimate is clipped to realistic INR market ranges post-estimation.
"""

import numpy as np
from typing import Tuple, Optional
from src.curves.ois_curve import OISCurve
from src.montecarlo.hull_white import HullWhite1F, calibrate_hw1f


class HullWhiteCalibrator:
    """
    Calibrates HW1F (a, sigma) from free historical MIBOR data.

    Both parameters are estimated via OLS on the discretised SDE.
    Since INR swaption vols are not freely available, sigma is anchored
    to realized MIBOR vol — this is the standard practice for emerging
    market rate desks without access to paid vol data.
    """

    def __init__(self, curve: OISCurve):
        self.curve = curve
        self.calibrated_a: Optional[float] = None
        self.calibrated_sigma: Optional[float] = None
        self.calibration_stats: dict = {}

    def calibrate_to_historical_mibor(self, n_days: int = 504) -> Tuple[float, float]:
        """
        Calibrate HW1F (a, sigma) from historical MIBOR using OLS.

        Uses calibrate_hw1f() from hull_white.py which runs the full
        OLS regression on the discretised SDE — both parameters are
        data-driven, not assumed.

        Data Note:
            Since INR swaption implied vols are not freely available,
            sigma is calibrated to realized MIBOR vol (a valid proxy
            used by market practitioners without Bloomberg access).
            Mean reversion 'a' is estimated from the autocorrelation
            structure of MIBOR via the OLS beta coefficient.

        Args:
            n_days: Days of MIBOR history to use (default 504 = 2 years).

        Returns:
            Tuple (a, sigma) — both calibrated from data.
        """
        from src.data_ingestion.market_data import get_historical_mibor

        df_mibor = get_historical_mibor(n_days=n_days)

        # Rates from get_historical_mibor() are in percent (e.g. 6.5 = 6.5%)
        # calibrate_hw1f() expects decimal values (0.065)
        rates_decimal = df_mibor['mibor_rate'] / 100.0

        # Run OLS calibration — estimates both a and sigma from data
        stats = calibrate_hw1f(rates_decimal)

        self.calibrated_a = stats['a']
        self.calibrated_sigma = stats['sigma']
        self.calibration_stats = stats

        return self.calibrated_a, self.calibrated_sigma

    def get_calibration_summary(self) -> dict:
        """
        Return calibration statistics for reporting/validation.

        Returns:
            Dict with a, sigma, theta_longrun, r_squared.
        """
        if not self.calibration_stats:
            self.calibrate_to_historical_mibor()
        return self.calibration_stats

    def get_calibrated_model(self) -> HullWhite1F:
        """Return a ready-to-use HW1F model with calibrated parameters."""
        if self.calibrated_sigma is None:
            self.calibrate_to_historical_mibor()
        return HullWhite1F(
            self.curve,
            a=self.calibrated_a,
            sigma=self.calibrated_sigma
        )
